### PR TITLE
:wrench: widen react peer dependency to include 17/18

### PR DESCRIPTION
**Pull request by wobo-jholmes**

### CODE REVIEW

**Comment by fabienjuif** [comment]
Hello I'll try to look at it this weekend :) 

Thank you !

**Comment by wobo-jholmes** [comment]
Thanks, it's not a huge switcharoo, just loosening up the `peerDependency` reference to allow it to work on projects that are using `react@17` or `react@18` for `npm` installs that are _strict_ about their peer dependency resolution.

**Comment by fabienjuif** [comment]
Hello @wobo-jholmes I just published the new version with your modification and some dependencies upgrades (dependabot ones too). The new version is 2.4.0: https://www.npmjs.com/package/use-bus

Thank you for the interest!

**Comment by fabienjuif** [comment]
Hey again @wobo-jholmes juste so you know, a new version is published: https://github.com/fabienjuif/use-bus/releases/tag/v2.5.0

**Pull request merged**
